<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
<!--    <link rel="stylesheet" type="text/css" href="public/css/main.css"/>-->
    <title>ПВИ Лабораторная 1</title>
<!--    <link rel="stylesheet" href="/css/normalize.css">-->
</head>
<body>
    <div class="page-content">
        <?php /** @var App\Model\View\Renderer $this */ ?>
        <?php $this->renderTemplate() ?>
    </div>
</body>
</html>