<?php /** @var \App\Model\View\Renderer $this */ ?>

<?php /** @var App\Model\Core\Entity\Collection $products */ ?>
<?php $products = $this->getData('products') ?>
<?php if ($products && $products->getSize()): ?>
    <h1>Товары</h1>
    <table class="entity-table">
        <tr>
            <th>Название</th>
            <th>Цена (руб.)</th>
            <th>Количество</th>
            <th>Изображение</th>
            <th>Действие</th>
        </tr>
        <?php /** @var App\Model\Product $_product */ ?>
        <?php while ($_product = $products->fetchItem()): ?>
            <tr>
                <td><div><?php echo $_product->getName() ?></div></td>
                <td><div><?php echo $_product->getPrice() . ' руб.' ?></div></td>
                <td><div><?php echo $_product->getQty() ?></div></td>
                <?php if ($_product->getImage()): ?>
                    <td>
                        <img src="<?php echo $_product->getImageUrl() ?>" alt="<?php echo $_product->getName() ?>"
                             width="30px" height="30px">
                    </td>
                <?php endif; ?>
                <td><a href="/admin/product/edit/?id=<?php echo $_product->getId() ?>">Редактировать</a></td>
            </tr>
        <?php endwhile; ?>
    </table>
<?php else: ?>
    <h1>Пока нет товаров :(</h1>
<?php endif; ?>
<br>
<a class="entity-add" href="/admin/product/new">Добавить</a>
