<?php /** @var \App\Model\View\Renderer $this */ ?>

<?php /** @var App\Model\Core\Entity\Collection $_products */ ?>
<?php $_products = $this->getData('products') ?>
<?php if ($_products && $_products->getSize()): ?>
    <h1>Товары</h1>
    <?php while ($_product = $_products->fetchItem()): ?>
        <div><?php echo $_product->getName() ?></div>
        <div><?php echo $_product->getPrice() . ' руб.' ?></div>
        <a href="/admin/productEdit/?id=<?php echo $_product->getId() ?>">Редактировать</a>
    <?php endwhile; ?>
<?php else: ?>
    <h1>Пока нет товаров :(</h1>
<?php endif; ?>
