<?php /** @var \App\Model\View\Renderer $this */ ?>

<?php
/** @var \App\Model\Core\Entity\Collection $categories */
$categories = $this->getData('categories');
?>
<h2>Добавить новую категорию</h2>
<div class="entity-edit">
    <form action="/admin/category/save" method="post" enctype="multipart/form-data">
        <div class="form__row">
            <label class="form__row-label" for="name">Название</label>
            <input type="text" name="category[name]" id="name"">
        </div>
        <input type="submit" value="Сохранить">
    </form>
</div>
